### ISSUE TITLE
Add gibberish salt after newline in commit message

### ISSUE THREAD

**Issue by pirate** [awentzonline/coolmit#3]
It would be nice to leave the short commit message untouched and instead add the appended gibberish to the commit message body, that way the salt doesn't show up in slack/git logs.

<img width="240" alt="screen shot 2015-12-24 at 3 08 30 pm" src="https://cloud.githubusercontent.com/assets/511499/11997687/378ef8d2-aa50-11e5-931c-b8ebb2d62c42.PNG">
<img width="559" alt="screen shot 2015-12-24 at 3 08 02 pm" src="https://cloud.githubusercontent.com/assets/511499/11997685/2c125b2a-aa50-11e5-86a3-f6c65713c6b6.PNG">

**Comment by awentzonline** [comment]
Thanks for the suggestion! I've made that update.

**Comment by awentzonline** [comment]
@pirate I figured out something a little better: turns out git isn't real strict about the commit header data so I'm putting the string in there and it seems to work. I think the only way to ever see it is by viewing the actual git object file.

**Comment by pirate** [comment]
Sweet, nice discovery @awentzonline!  Thanks for updating it.
